sudo: false
language: ruby
rvm:
 - 2.4.1
services:
  - postgresql
before_install:
  - gem update --system
install:
  - bundle install --jobs=3 --retry=3 --deployment
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script:
  - bundle exec rake
#  - bundle exec rubocop
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
