sudo: false
language: ruby
rvm:
 - 2.4.1
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
before_install:
  - gem update --system
install:
  - bundle install --jobs=3 --retry=3 --deployment
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
script:
  - bundle exec rake
#  - bundle exec rubocop
