require 'ffaker'

10.times do
  FactoryBot.create(                     :song_review, :published, body: FFaker::HipsterIpsum.paragraphs( 3).join("\n\n"))
  FactoryBot.create(                     :song_review, :published, body: FFaker::HipsterIpsum.paragraphs(11).join("\n\n"))
  FactoryBot.create(                 :standalone_post, :published, body: FFaker::HipsterIpsum.paragraphs( 5).join("\n\n"))
  FactoryBot.create(                    :album_review, :published, body: FFaker::HipsterIpsum.paragraphs( 9).join("\n\n"))
  FactoryBot.create(                    :movie_review, :published, body: FFaker::HipsterIpsum.paragraphs( 5).join("\n\n"))
  FactoryBot.create(                 :standalone_post, :published, body: FFaker::HipsterIpsum.paragraphs(17).join("\n\n"))
  FactoryBot.create(                     :song_review, :published, body: FFaker::HipsterIpsum.paragraphs( 3).join("\n\n"))
  FactoryBot.create(                  :tv_show_review, :published, body: FFaker::HipsterIpsum.paragraphs( 2).join("\n\n"))
  FactoryBot.create(                 :hardware_review, :published, body: FFaker::HipsterIpsum.paragraphs(45).join("\n\n"))
  FactoryBot.create(                     :game_review, :published, body: FFaker::HipsterIpsum.paragraphs( 9).join("\n\n"))
  FactoryBot.create(                     :book_review, :published, body: FFaker::HipsterIpsum.paragraphs( 4).join("\n\n"))
  FactoryBot.create(                     :song_review, :published, body: FFaker::HipsterIpsum.paragraphs( 3).join("\n\n"))
  FactoryBot.create(                    :album_review, :published, body: FFaker::HipsterIpsum.paragraphs(15).join("\n\n"))
  FactoryBot.create(                 :standalone_post, :published, body: FFaker::HipsterIpsum.paragraphs( 9).join("\n\n"))
  FactoryBot.create(                 :software_review, :published, body: FFaker::HipsterIpsum.paragraphs( 1).join("\n\n"))
  FactoryBot.create(                     :song_review, :published, body: FFaker::HipsterIpsum.paragraphs(11).join("\n\n"))
  FactoryBot.create(                 :standalone_post, :published, body: FFaker::HipsterIpsum.paragraphs( 2).join("\n\n"))
  FactoryBot.create(                     :game_review, :published, body: FFaker::HipsterIpsum.paragraphs( 1).join("\n\n"))
  FactoryBot.create(                 :hardware_review, :published, body: FFaker::HipsterIpsum.paragraphs( 3).join("\n\n"))
  FactoryBot.create(                 :standalone_post, :published, body: FFaker::HipsterIpsum.paragraphs( 2).join("\n\n"))
  FactoryBot.create(                  :podcast_review, :published, body: FFaker::HipsterIpsum.paragraphs(12).join("\n\n"))
  FactoryBot.create(                :newspaper_review, :published, body: FFaker::HipsterIpsum.paragraphs( 5).join("\n\n"))
  FactoryBot.create(                 :magazine_review, :published, body: FFaker::HipsterIpsum.paragraphs( 4).join("\n\n"))
  FactoryBot.create(                  :product_review, :published, body: FFaker::HipsterIpsum.paragraphs( 3).join("\n\n"))
  FactoryBot.create(                    :comic_review, :published, body: FFaker::HipsterIpsum.paragraphs( 3).join("\n\n"))
  FactoryBot.create(                     :song_review, :published, body: FFaker::HipsterIpsum.paragraphs( 2).join("\n\n"))
  FactoryBot.create(                  :artwork_review, :published, body: FFaker::HipsterIpsum.paragraphs(10).join("\n\n"))
  FactoryBot.create(                     :game_review, :published, body: FFaker::HipsterIpsum.paragraphs(22).join("\n\n"))
  FactoryBot.create(                 :standalone_post, :published, body: FFaker::HipsterIpsum.paragraphs(12).join("\n\n"))
  FactoryBot.create(                 :software_review, :published, body: FFaker::HipsterIpsum.paragraphs(20).join("\n\n"))
  FactoryBot.create(               :radio_show_review, :published, body: FFaker::HipsterIpsum.paragraphs(10).join("\n\n"))
  FactoryBot.create(                  :podcast_review, :published, body: FFaker::HipsterIpsum.paragraphs(15).join("\n\n"))

  FactoryBot.create(       :collaborative_book_review, :published, body: FFaker::HipsterIpsum.paragraphs( 6).join("\n\n"))
  FactoryBot.create(       :collaborative_song_review, :published, body: FFaker::HipsterIpsum.paragraphs( 9).join("\n\n"))
  FactoryBot.create(      :collaborative_album_review, :published, body: FFaker::HipsterIpsum.paragraphs( 7).join("\n\n"))
  FactoryBot.create(    :collaborative_podcast_review, :published, body: FFaker::HipsterIpsum.paragraphs( 5).join("\n\n"))
  FactoryBot.create( :collaborative_radio_show_review, :published, body: FFaker::HipsterIpsum.paragraphs( 4).join("\n\n"))
  FactoryBot.create(   :collaborative_hardware_review, :published, body: FFaker::HipsterIpsum.paragraphs( 3).join("\n\n"))
  FactoryBot.create(  :collaborative_newspaper_review, :published, body: FFaker::HipsterIpsum.paragraphs( 2).join("\n\n"))
  FactoryBot.create(   :collaborative_magazine_review, :published, body: FFaker::HipsterIpsum.paragraphs( 1).join("\n\n"))
  FactoryBot.create(      :collaborative_comic_review, :published, body: FFaker::HipsterIpsum.paragraphs( 8).join("\n\n"))
  FactoryBot.create(    :collaborative_artwork_review, :published, body: FFaker::HipsterIpsum.paragraphs( 1).join("\n\n"))
  FactoryBot.create(      :collaborative_movie_review, :published, body: FFaker::HipsterIpsum.paragraphs( 4).join("\n\n"))
  FactoryBot.create(    :collaborative_tv_show_review, :published, body: FFaker::HipsterIpsum.paragraphs( 2).join("\n\n"))
  FactoryBot.create(       :collaborative_game_review, :published, body: FFaker::HipsterIpsum.paragraphs(11).join("\n\n"))
  FactoryBot.create(   :collaborative_software_review, :published, body: FFaker::HipsterIpsum.paragraphs( 9).join("\n\n"))
  FactoryBot.create(    :collaborative_product_review, :published, body: FFaker::HipsterIpsum.paragraphs( 4).join("\n\n"))
end